In [2]:
import numpy as np
import scipy as sci

### Question 1: Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [4]:
def greater_elem_arr(arr1,arr2):
    if(arr1.shape==arr2.shape):
        return arr1>arr2

def lesser_elem_arr(arr1,arr2):
    if(arr1.shape==arr2.shape):
        return arr1<arr2

def greaterequal_arr(arr1,arr2):
    if(arr1.shape==arr2.shape):
        return arr1>=arr2

def lesserequal_arr(arr1,arr2):
    if(arr1.shape==arr2.shape):
        return arr1<=arr2
    
arr1=np.array([[5,3],
               [4,6]])

arr2=np.array([[5,4],
               [2,6]])

print("Element wise comparison of arrays for greater element:",greater_elem_arr(arr1,arr2))
print("Element wise comparison of arrays for lesser element:",lesser_elem_arr(arr1,arr2))
print("Element wise comparison of arrays for greaterthan or equal element:",greaterequal_arr(arr1,arr2))
print("Element wise comparison of arrays for lesser than or equal element:",lesserequal_arr(arr1,arr2))

Element wise comparison of arrays for greater element: [[False False]
 [ True False]]
Element wise comparison of arrays for lesser element: [[False  True]
 [False False]]
Element wise comparison of arrays for greaterthan or equal element: [[ True False]
 [ True  True]]
Element wise comparison of arrays for lesser than or equal element: [[ True  True]
 [False  True]]


### Question 2: Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [13]:
# creating an array of 10 zeros
print(np.zeros([2,5])) # shape of this array is 2x5
print(np.zeros([1,10])) # shape of this array is 2x5

# creating an array of 10 ones
print(np.ones([2,5])) # shape of this array is 2x5
print(np.ones([1,10])) # shape of this array is 2x5

# creating an array of 10 zeros
print(np.full([2,5],5)) # shape of this array is 2x5
print(np.full([1,10],5)) # shape of this array is 2x5

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[5 5 5 5 5]
 [5 5 5 5 5]]
[[5 5 5 5 5 5 5 5 5 5]]


### Question 3: Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array

In [4]:
array1=np.array([[4,3,5],
                 [2,6,7],
                [3,4,8]])
print("Original array:\n",array1)
print("Sum of all elements:\n",np.sum(array1))
print("Sum of each column:\n",np.sum(array1, axis=0))
print("Sum of each row:\n",np.sum(array1, axis=1))

Original array:
 [[4 3 5]
 [2 6 7]
 [3 4 8]]
Sum of all elements:
 42
Sum of each column:
 [ 9 13 20]
Sum of each row:
 [12 15 15]


### Question 4: Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [17]:
def add_arrays(ar1,ar2):
    return ar1+ar2

def sub_arrays(ar1,ar2):
    return ar1-ar2

def mul_arrays(ar1,ar2):
    return ar1*ar2

def div_arrays(ar1,ar2):
    return ar1/ar2

array1=np.array([[9,5,3],
                [4,6,8]])
array2=np.array([[3,2,1],
                [2,6,4]])

print("Addition of array1 and array2 is:",add_arrays(array1,array2))
print("Subtraction of array1 and array2 is:",sub_arrays(array1,array2))
print("Multiplication of array1 and array2 is:",mul_arrays(array1,array2))
print("Division of array1 and array2 is:",div_arrays(array1,array2))

Addition of array1 and array2 is: [[12  7  4]
 [ 6 12 12]]
Subtraction of array1 and array2 is: [[6 3 2]
 [2 0 4]]
Multiplication of array1 and array2 is: [[27 10  3]
 [ 8 36 32]]
Division of array1 and array2 is: [[3.  2.5 3. ]
 [2.  1.  2. ]]


### Question 5: Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in degree.

In [19]:
array1=np.array([[3,4,6],
                [4,5,7]])
print("Trigonometric Sine of array1 is:",np.sin(array1))
print("Trigonometric Cosine of array1 is:",np.cos(array1))
print("Trigonometric Tangent of array1 is:",np.tan(array1))

Trigonometric Sine of array1 is: [[ 0.14112001 -0.7568025  -0.2794155 ]
 [-0.7568025  -0.95892427  0.6569866 ]]
Trigonometric Cosine of array1 is: [[-0.9899925  -0.65364362  0.96017029]
 [-0.65364362  0.28366219  0.75390225]]
Trigonometric Tangent of array1 is: [[-0.14254654  1.15782128 -0.29100619]
 [ 1.15782128 -3.38051501  0.87144798]]
